[env:uno]
platform  = atmelavr
board     = uno
framework = arduino

; Serial monitor baud rate
monitor_speed = 9600

; Library dependencies (PlatformIO will auto-download these)
lib_deps =
    adafruit/RTClib @ ^2.1.1
